version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    container_name: crave-db
    restart: always
    environment:
      POSTGRES_USER: deluxan
      POSTGRES_PASSWORD: deluxan123
      POSTGRES_DB: crave
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - crave-network

volumes:
  pgdata:

networks:
  crave-network:
    driver: bridge
